# Generated by Django 6.0.3 on 2026-04-27 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.AddField(
            model_name='appuser',
            name='userid',
            field=models.OneToOneField(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_profile', to='api.login'),
        ),
    ]
