# Generated by Django 6.0.3 on 2026-04-27 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_login_appuser_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.TextField()),
                ('finished', models.BooleanField(default=False)),
                ('createddatetime', models.DateTimeField(auto_now_add=True)),
                ('finisheddatetime', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.taskevent')),
            ],
            options={
                'db_table': 'subtasks',
            },
        ),
    ]
