# Generated by Django 6.0.3 on 2026-04-27 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_subtask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='finished',
            field=models.CharField(default='False', max_length=50),
        ),
    ]
