# Generated by Django 6.0.3 on 2026-04-27 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_subtask_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskevent',
            name='user',
            field=models.ForeignKey(db_column='user', on_delete=django.db.models.deletion.CASCADE, related_name='task_events', to='api.login'),
        ),
    ]
