# Generated by Django 6.0.3 on 2026-05-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_taskevent_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='task_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='task_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
