# Generated by Django 6.0.3 on 2026-05-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_taskevent_task_end_time_taskevent_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('FINISHED', 'FINISHED'), ('NOT FINISHED', 'NOT FINISHED'), ('SKIPPED', 'SKIPPED')], default='PENDING', max_length=20),
        ),
    ]
