# Generated by Django 6.0.3 on 2026-05-02 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_taskevent_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(unique=True)),
                ('target', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'level_targets',
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='UserLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('exp', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(db_column='userid', on_delete=django.db.models.deletion.CASCADE, related_name='user_level', to='api.login')),
            ],
            options={
                'db_table': 'user_levels',
            },
        ),
    ]
