# Generated by Django 6.0.3 on 2026-05-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_level_userlevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskevent',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
